# Generated by Django 4.1.3 on 2023-02-09 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('reviews', '0002_review_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile'),
            preserve_default=False,
        ),
    ]
