# Generated by Django 4.1.3 on 2023-02-11 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_product_image'),
        ('reviews', '0007_alter_review_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.product'),
            preserve_default=False,
        ),
    ]
