# Generated by Django 4.1.3 on 2022-11-27 13:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_contact_contactform'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
